# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hw2-1to4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(243, 473)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_load_folder = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_load_folder.setObjectName("btn_load_folder")
        self.gridLayout.addWidget(self.btn_load_folder, 6, 0, 1, 1)
        self.label_0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_0.setObjectName("label_0")
        self.gridLayout.addWidget(self.label_0, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.btn_2_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_2_1.setObjectName("btn_2_1")
        self.gridLayout.addWidget(self.btn_2_1, 11, 0, 1, 1)
        self.btn_load_img = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_load_img.setObjectName("btn_load_img")
        self.gridLayout.addWidget(self.btn_load_img, 4, 0, 1, 1)
        self.btn_1_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_1_1.setObjectName("btn_1_1")
        self.gridLayout.addWidget(self.btn_1_1, 9, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.btn_4_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_4_2.setObjectName("btn_4_2")
        self.gridLayout.addWidget(self.btn_4_2, 17, 0, 1, 1)
        self.btn_3_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_3_1.setObjectName("btn_3_1")
        self.gridLayout.addWidget(self.btn_3_1, 14, 0, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 10, 0, 1, 1)
        self.btn_2_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_2_2.setObjectName("btn_2_2")
        self.gridLayout.addWidget(self.btn_2_2, 12, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 15, 0, 1, 1)
        self.btn_4_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_4_1.setObjectName("btn_4_1")
        self.gridLayout.addWidget(self.btn_4_1, 16, 0, 1, 1)
        self.btn_load_video = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_load_video.setObjectName("btn_load_video")
        self.gridLayout.addWidget(self.btn_load_video, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 243, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_load_folder.setText(_translate("MainWindow", "Load Folder"))
        self.label_0.setText(_translate("MainWindow", "No video loaded"))
        self.label_5.setText(_translate("MainWindow", "3. Perspective Transform"))
        self.label_3.setText(_translate("MainWindow", "1. Background Subtraction"))
        self.btn_2_1.setText(_translate("MainWindow", "2.1 Preprocessing"))
        self.btn_load_img.setText(_translate("MainWindow", "Load Image"))
        self.btn_1_1.setText(_translate("MainWindow", "1.1 Background Subtraction"))
        self.label_2.setText(_translate("MainWindow", "No folder loaded"))
        self.btn_4_2.setText(_translate("MainWindow", "4.2 Compute the Reconstruction Error"))
        self.btn_3_1.setText(_translate("MainWindow", "3.1 Perspective Transform"))
        self.label_1.setText(_translate("MainWindow", "No image loaded"))
        self.label_4.setText(_translate("MainWindow", "2. Optical Flow"))
        self.btn_2_2.setText(_translate("MainWindow", "2.2 Video Tracking"))
        self.label_6.setText(_translate("MainWindow", "4. PCA"))
        self.btn_4_1.setText(_translate("MainWindow", "4.1 Image Reconstruction"))
        self.btn_load_video.setText(_translate("MainWindow", "Load Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
