# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cvdl_hw1-2-4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(298, 393)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box.setGeometry(QtCore.QRect(50, 40, 191, 281))
        self.group_box.setObjectName("group_box")
        self.load_img1 = QtWidgets.QPushButton(self.group_box)
        self.load_img1.setGeometry(QtCore.QRect(0, 30, 191, 31))
        self.load_img1.setObjectName("load_img1")
        self.load_img2 = QtWidgets.QPushButton(self.group_box)
        self.load_img2.setGeometry(QtCore.QRect(0, 90, 191, 31))
        self.load_img2.setObjectName("load_img2")
        self.btn4_1 = QtWidgets.QPushButton(self.group_box)
        self.btn4_1.setGeometry(QtCore.QRect(0, 160, 191, 31))
        self.btn4_1.setObjectName("btn4_1")
        self.btn4_2 = QtWidgets.QPushButton(self.group_box)
        self.btn4_2.setGeometry(QtCore.QRect(0, 230, 191, 31))
        self.btn4_2.setObjectName("btn4_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 298, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_box.setTitle(_translate("MainWindow", "4. SIFT"))
        self.load_img1.setText(_translate("MainWindow", "Loag Image 1"))
        self.load_img2.setText(_translate("MainWindow", "Load Image 2"))
        self.btn4_1.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.btn4_2.setText(_translate("MainWindow", "4.2 Matched Keypoints"))
