# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cvdl_hw1-2-5.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.group_box.setGeometry(QtCore.QRect(40, 150, 221, 261))
        self.group_box.setObjectName("group_box")
        self.btn5_1 = QtWidgets.QPushButton(self.group_box)
        self.btn5_1.setGeometry(QtCore.QRect(0, 60, 221, 31))
        self.btn5_1.setObjectName("btn5_1")
        self.btn5_2 = QtWidgets.QPushButton(self.group_box)
        self.btn5_2.setGeometry(QtCore.QRect(0, 100, 221, 31))
        self.btn5_2.setObjectName("btn5_2")
        self.btn5_3 = QtWidgets.QPushButton(self.group_box)
        self.btn5_3.setGeometry(QtCore.QRect(0, 140, 221, 31))
        self.btn5_3.setObjectName("btn5_3")
        self.btn5_4 = QtWidgets.QPushButton(self.group_box)
        self.btn5_4.setGeometry(QtCore.QRect(0, 180, 221, 31))
        self.btn5_4.setObjectName("btn5_4")
        self.btn5_5 = QtWidgets.QPushButton(self.group_box)
        self.btn5_5.setGeometry(QtCore.QRect(0, 220, 221, 31))
        self.btn5_5.setObjectName("btn5_5")
        self.load_img = QtWidgets.QPushButton(self.group_box)
        self.load_img.setGeometry(QtCore.QRect(0, 20, 221, 31))
        self.load_img.setObjectName("load_img")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 80, 411, 401))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 40, 121, 31))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_box.setTitle(_translate("MainWindow", "5. Restnet 101 test"))
        self.btn5_1.setText(_translate("MainWindow", "1. Show Train Images"))
        self.btn5_2.setText(_translate("MainWindow", "2. Show Model Structure"))
        self.btn5_3.setText(_translate("MainWindow", "3. Show Data Augmentation"))
        self.btn5_4.setText(_translate("MainWindow", "4. Show Accuracy and Loss"))
        self.btn5_5.setText(_translate("MainWindow", "5. Inference"))
        self.load_img.setText(_translate("MainWindow", "Load Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
